HW by Tim Mironchuk
AufarZakiev/CPP-2019-2020-Threading pull request #4
Opened 2020-04-23 13:54 UTC by Limberjack

2020-04-23 14:09 UTC, AufarZakiev requested changes

2020-04-23 14:09 UTC, AufarZakiev commented on task1.cpp
> +std::vector<int>& setupVector(std::vector<int>& vec, int size)
std::generate есть для этого)

2020-04-23 14:09 UTC, AufarZakiev commented on task1.cpp
> +void task1();
зачем раннее объявление?

2020-04-23 14:09 UTC, AufarZakiev commented on task1.cpp
> +  std::thread** threads = new std::thread*[threadNum];
Нужен массив чего-нибудь - используй vector или array, зачем эта морока с указателями

2020-04-23 14:09 UTC, AufarZakiev commented on task3.cpp
> +  for (int i = 0; i < result.size(); i++)
Где же многопоточное сложение?
Загляните в реквесты Кирилла, посмотрите, как можно сильно сократить ваш код с помощью async

2020-04-27 05:20 UTC, Limberjack commented on task3.cpp
> +  for (int i = 0; i < result.size(); i++)
task3 не актуальный. я не понял чего от меня хотят в самом задании, так что этот файл ничем не отличается от task2

2020-04-27 05:21 UTC, Limberjack commented on task1.cpp
> +void task1();
чтобы я не забыл про то, какие методы надо было сделать

2020-05-21 07:26 UTC, AufarZakiev requested changes

2020-05-21 07:26 UTC, AufarZakiev commented on task3.cpp
> +    wait();
wait() в цикле? Это работает не так. Каждый поток вызывает wait() один раз, потом просыпается после получения notify()  и продолжает работу. Надо исправить

2020-05-21 14:56 UTC, AufarZakiev requested changes

2020-05-21 14:56 UTC, AufarZakiev commented on task3.cpp
> +    threads[i] = new std::thread(std::async([&]() {
Зачем поток создавать на куче?

2020-05-21 15:05 UTC, Limberjack commented on task3.cpp
> +    threads[i] = new std::thread(std::async([&]() {
переделал

2020-05-21 15:09 UTC, AufarZakiev approved these changes

2022-05-18 21:23 UTC, closed without merging